-- AlterTable
ALTER TABLE `AuditLog` MODIFY `action` ENUM('LOGIN', 'LOGIN_FAILED', 'LOGOUT', 'PATIENT_CREATE', 'PATIENT_UPDATE', 'RULE_CHANGE', 'CATEGORY_CHANGE', 'CARD_LINK', 'CARD_BLOCK', 'CARD_UNBLOCK', 'CARD_REPLACE', 'CARD_STOCK', 'CREDIT', 'REDEMPTION', 'ADJUSTMENT', 'REVERSAL', 'REPORT_EXPORT', 'PERMISSION_CHANGE', 'SETTINGS_CHANGE', 'OTP_REQUEST', 'MODULE_TOGGLE', 'TAG_ASSIGN', 'TAG_REMOVE', 'SEGMENT_CHANGE', 'TEMPLATE_CHANGE', 'COMMUNICATION_SEND', 'AUTOMATION_RUN', 'AUTOMATION_CHANGE', 'REFERRAL_CREATE', 'REFERRAL_CONVERT', 'NPS_RESPONSE', 'REWARD_REDEEM', 'VOUCHER_ISSUE', 'VOUCHER_REDEEM', 'GIFT_CARD', 'CONSENT_CHANGE', 'ACCELERATOR_CHANGE', 'API_KEY_CHANGE', 'WEBHOOK_DELIVERY', 'ONBOARDING_STEP', 'RAFFLE_CHANGE', 'RECEIPT_REVIEW', 'PREDICTION_RUN', 'PUSH_DEVICE', 'SCHEDULE_CHANGE', 'AFFILIATE_APPROVE', 'AFFILIATE_REJECT', 'AFFILIATE_SUSPEND', 'AFFILIATE_BLOCK', 'AFFILIATE_REACTIVATE', 'AFFILIATE_PLAN_CHANGE', 'AFFILIATE_REFERRAL_LINK', 'AFFILIATE_COMMISSION_BLOCK', 'AFFILIATE_COMMISSION_CANCEL', 'AFFILIATE_PAYOUT', 'AFFILIATE_PROFILE_CHANGE', 'PLATFORM_SALE_CONFIRM', 'PLATFORM_SALE_CANCEL', 'VIDEOCALL_CHANGE', 'OTHER') NOT NULL;

-- AlterTable
ALTER TABLE `VideoCallRecording` ADD COLUMN `organizationId` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `VideoCallSignal` ADD COLUMN `organizationId` VARCHAR(191) NULL;

-- CreateIndex
CREATE INDEX `VideoCallRecording_organizationId_idx` ON `VideoCallRecording`(`organizationId`);

-- CreateIndex
CREATE INDEX `VideoCallSignal_organizationId_idx` ON `VideoCallSignal`(`organizationId`);
